name: Build and release
on: [workflow_dispatch]

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Create release
              uses: ncipollo/release-action@v1
              env:
                  version: v0.0.1-${{ github.run_number }}
              with:
                  artifacts: "build/*.css"
                  tag: ${{ env.version }}
                  commit: "master"
                  token: ${{ secrets.GITHUB_TOKEN }}
