name: Build and release
on: [workflow_dispatch]

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: tagging debug
              run: env
            - name: Create release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "build/*.css"
                  tag: "i hate this"
                  commit: "master"
                  token: ${{ secrets.GITHUB_TOKEN }}
