name: Test workflow
on: [workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Testing
                  tag: ${{ env.GITHUB_RUN_NUMBER }}
                  token: ${{ secrets.GITHUB_TOKEN }}
            - run: env
